server:
  servlet:
    context-path: /desafio-1/v1/
    encoding:
      charset: UTF-8
      force-response: true

spring:
  messages:
    basename:
    - messages
  application:
    name: 'primeiro-desafio'
  datasource:
    url: jdbc:h2:mem:dcbapp
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
